### PR TITLE
fixed android mmyy

### LINKED ISSUE #13: Getting wrong expiration month and year
I seem to be getting the wrong expMonth and expYear:

    <stripe:CreditCardView #ccview></stripe:CreditCardView>
    ....
    @ViewChild('ccview') ccRef: ElementRef<CreditCardView>;
    
    const card = this.ccRef.nativeElement.card;
    console.log("got card", card.expMonth, card.expYear, card.cvc, card.number);

The CVC and card number show up just fine. But the widget gives e.g. "1053187" and "1053279" when I input 12/22 for example -- this is on Android, haven't tested iOS yet. Any ideas?

### PR DESCRIPTION
**Pull request by neil-119**
Fixes #13

### CODE REVIEW

**Comment by carlosanjos** [comment]
I also created the pull request https://github.com/triniwiz/nativescript-stripe/pull/15 that also updates the SDK version and sorta fixes mmyy as well. With both pull requests combined it should be bulletproof. :)

**Comment by triniwiz** [comment]
Thank you

**Comment by neil-119** [comment]
Won't merging this and #15 at the same time cause typescript compilation problems from changing `any` to `number` since the latter won't have intValue()?

**Comment by triniwiz** [comment]
@neil-119 i'm going to do some updates since the plugin needs to add support for v4

**Comment by neil-119** [comment]
Great. Let me know if you'd like help testing it.

**Comment by triniwiz** [comment]
Feel free to test away

**Comment by neil-119** [comment]
Still seeing expiry date is invalid error on the latest Nativescript 4.2.0 with the build published 3 days ago. Changing the expiration month/year to `any` and then calling `intValue()` fixes it.

Edit -- nice work cleaning up the plugin though!

**Comment by carlosanjos** [comment]
@neil-119 Do you mind sending your pull request again? I'm seeing the `Your card's expiration year is invalid.` error again.

**Pull request merged**
