### PR TITLE
feat(demo-angular-custom): add support for Custom Integration to demo-angular

### LINKED ISSUE #24: Add Support for Custom Integration to Angular demo
Add support for the Custom integration to the angular demo app in `./demo-angular`. 

This requires slightly modifying the Custom Integration to make it more similar across platforms.

It also requires updating the `./angular` package to include directives, following the instructions for supporting Angular in [Supporting Angular in UI Plugins](https://docs.nativescript.org/angular/plugins/angular-plugin). This changes the instructions for using the plugin with Angular.

### PR DESCRIPTION
**Pull request by RobertGardner**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included

## What is the new behavior?
Add a demo of Custom Integration's CreditCardView to the `demo-angular` app.

This updates the way the plugin supports Angular to follow the [new guidelines](https://docs.nativescript.org/angular/plugins/angular-plugin).

This makes some changes to the Custom Integration API to make it similar across platforms:

* `Card` now implements a new interface `CardCommon`
* `Stripe.createToken` now takes a `Card` (or `CardCommon`) instead of a native object
* `Card.card` has been replaced with `Card.native`

Closes #24 

BREAKING CHANGES:

See above. APIs for registering in Angular and `createToken` have changed.

Migration steps:

* Follow the instructions in the README for using Angular.
* Change all calls to `Stripe.createToken` to take `card` instead of `card.card`.
* If you use the native interface (`card.card`) consider using `CardCommon` instead. If you still need the native interface, change `card.card` to `card.native`.

### CODE REVIEW

**Comment by RobertGardner** [comment]
Note:

I am leaving town for 2 weeks but I believe this is ready to submit, or I'll be able to easily fix things once I return.

I thought I would send this PR now to give you the next two weeks to look over the changes. Since it introduces breaking changes, you should consider the impact of those changes and let me know if they are acceptable or should be rolled back.

**Comment by RobertGardner** [comment]
I'm back and anxious to wrap up this effort. Have you had a chance to look it over?

I had one thought about how to make this more backward-compatible. The Angular changes I'd like to keep since this is a more standard way to use a plugin with Angular. For the Card API change, I could change it as follows:

I changed `createToken()` to take a `CardCommon` instead of a native object (`any`). To make the change backward-compatible, I could keep the API the same, but check the parameter to see if it is a native object and use that. Something like:

```
createToken(card: CardCommon) {
  let c: STPCardParams;
  if (card instanceof STPCardParams)
    c = card;
  else
    c = card.native;
  //...
}
```

I'm not sure if this is necessary since making the change to the new API is very simple, but I could do that if backward-compatibility is important.

**Comment by triniwiz** [comment]
LGTM you don't need to make it compatible because with all the breaking changes we can introduce a new major version

**Comment by RobertGardner** [comment]
Makes sense. I was going to publish it as version 4.2.0. Should I change it to 5.0.0?

**Comment by triniwiz** [comment]
Yes

**Pull request merged**
