### PR TITLE
Feature/nativescript 7 compat

### PR DESCRIPTION
**Pull request by trane77**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included **(code has not been updated)** 

## What is the current behavior?
Loading CreditCardViewModule in a Nativescript-Angular project with Angular v10 causes a problem when running `tns build <platform>`

## What is the new behavior?
image

- The plugin has been updated in order to be compatible with the new Angular Ivy compiler and Nativescript >= 6.8.0
- Demo projects imports have been updated, now they use Nativescript's scoped packages
- The plugin packaging script has been updated to comply with the new build flow
- Version has been set to `7.0.1-rc.0`, even if everything is compiling correctly, the original html markup supplied with the plugin needs a revision, and proper testing should be considered on both platforms, before to release these changes as 'stable'.

Fixes/Implements/Closes #[Issue Number].
#125

### CODE REVIEW

**Comment by RobertGardner** [comment]
I'm not able to run this. I must be doing something wrong?
I cloned your repository, then ran:
```
cd src
npm run build
npm run demo-angular.android
```
It installs on the emulator but crashes with:
```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication:
com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.
If using typescript make sure your entry point file is transpiled to javascript.
```
I have a similar problem on iOS when I run `npm run demo-angular.ios`:
```
JavaScript error:
file: node_modules/@nativescript/core/application/index.ios.js:417:0: JS ERROR Error: Root should be either UIViewController or UIView
```
Can you give me some guidance on how to make sure this is working?

**Comment by trane77** [comment]
Hello @RobertGardner, 
Thanks for reporting the issue, I just pushed an update where all the runtimes are at the latest version available. 
Actually I'm away from home and configuring my laptop in order to run the application.

Can you try to pull and run it again, while I get my computer ready? thank you

**Comment by trane77** [comment]
@RobertGardner I've just pushed a new version which depends on @nativescript/angular 10.0.0-rc.5, I don't know why but later versions are leading to an exception when the application starts. 
I knew how to fix it due to the same problem happening in another application of mine... The issue was notified to {N} team ([issue #2197](https://github.com/NativeScript/nativescript-angular/issues/2197)) I thought they fixed it in the stable release, but it's not. Probably it's a corner case that happens in a determined situation, I'll notify it again, to see if we can find the cause. 

Anyway, if you pull the last version, you should be able to run the application and see that's working. 

Cheers

**Comment by RobertGardner** [comment]
On Android unfortunately, I'm getting the exact same error. However, based on an earlier experience, on a whim I built a plugin package (using `publish/pack.sh`) and changed `demo-angular/package.json` to reference `nativescript-stripe` as `file:../publish/package/nativescript-stripe-7.0.1-rc.0.tgz` instead of as `file:../src`. It runs! But with some problems:

* "Custom Integration" works (I get tokens, sources, etc)
* "Intent Integration" works (all buttons give intents, etc)
* "Images" works
* "Standard Integration" links crash the app with no error messages anywhere that I can find. I have a suspicion that this is due to the problems I've encountered with {N} and Kotlin, but I don't have time right now to chase that down.

On iOS with the original `package.json` it crashes, but with a different error `Could not find module './'`. So I tried with the above change. That version runs, but it has very strange behavior. The very first time I launch the app the links on the home page work, but once I navigate back to the home page, none of them work. I don't have time right now to chase that down.

Here is the behavior of the pages when I tap them on first launch:


* "Custom Integration" works (I get tokens, sources, etc)
* "Images" works
* "Standard Integration" links don't do anything, no error messages anywhere that I can find
* "Intent Integration" crashes with
```
CONSOLE ERROR file: node_modules/@angular/core/fesm2015/core.js:4197:0: ERROR Error: Uncaught (in promise): Error: This value is not a native object.
new([native code])
at StripeCustomerSession(file: node_modules/nativescript-stripe/standard/standard.ios.js:45:0)
at StripeService(file: app/demo/stripe.service.ts:37:52)
at StripeService_Factory(file: app/demo/stripe.service.ts:21:26)
```

So it looks like I can no longer use `file:../src` to reference my plugin but will need to package it each edit/build/run cycle. I'm not thrilled by that, but I guess I can live with it, at a loss in productivity. What are other plugins doing to have an efficient development cycle?

I apologize for not having time right now to chase down the other crashes. I am very busy right now with several pressing projects.

**Comment by trane77** [comment]
Well... That's all interesting information, unfortunately I'm not that expert with Angular & Nativescript, so I'm trying to understand the whole process in depth by doing this migration!
I don't have a Mac at the moment so all the test that I've done are targeted to Android platform. I didn't face the error that you reported when using the plugin in the external project, because I'm importing the `tgz` there too, I always used that method instead of using symbolic links, because I wanted to reproduce the exact behavior of an user downloading the plugin. Apart from this I noticed that there are some differences between a project run inside the plugin path (like the `demo-angular` project) and an external project: the latter is giving me some errors related to missing references in the html markup. 

To give you an example:
image

Probably the `card` reference must be replaced with `$event` and it will be fixed, but I still don't get why the same template  markup in `demo-angular` is compiling without any problems!

What version of nativescript have you installed globally? On my pc I've got the 6.8.0 (stable), I can compile the `demo-angular` project without replacing the refrence to the plugin in the package.json to the tgz version, I left "../src" and actaully the application starts... I see the main view, but there when I tap on a button nothing happens: just one time I tapped the "show images" button and it opened the related view; once I went back to main view, it didn't work the second time.

Maybe there's a releation with all this and the fact that the demo folders are containing two `tsconfig.json` files? I see an *.esm.js and one *.tns.js. I don't exclude that the current  config of the demo projects is not right:

```
        "module": "commonjs",
        "target": "es5",
```
While the plugin's tsconfig edited by @NathanWalker is using:
```
    "target"              : "es2017",
    "module"              : "esnext",
    "moduleResolution"    : "node",
```

Don't ask me the difference because I'm a bit confused about this topic, I suppose that it changes how modules are packed, but even if guides can be found, it's still kinda obscure to me how NS handles these two configs, and what it needs to pack the plugin with the correct structure. 

I did a slight change in the `pack.sh`, just by removing the line where `ngc` was called: since now there's a new build step (build.angular) the compiled sources are placed in the `src/angular` folder, I suppose that there is no need compile them twice.

Which version of Node are you using? I've got the latest LTS installed, which is v12.18.3.
Also when changing the sources in the plugin, or a npm dependency, be sure to run the `clean` script instead of just `npm i  && npm run build`.

I totally agree with the fact that the build process must be improved if possible...I'm on a not very performant machine now, and running the build every time is taking a lot. It's not much productivity-friendly :) 

Don't apologize, we are all busy I think!  And now it's time for summer holidays! :smile: Jokes apart, I like how this plugin is made, it's clear that it required some time to be made. 

Cheers
F. 

**EDIT:**
Running the demo app:
1) It asks for the test api key (which I didn't set :duck:)
2) After clicking the buttons for a while it starts to print:

```
JS: Error: Cannot instantiate cyclic dependency! StripeService
JS:     at new ZoneAwareError (file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)
JS:     at throwCyclicDependencyError (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:5438:0)
JS:     at R3Injector.hydrate (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11215:0)
JS:     at R3Injector.get (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11041:0)
JS:     at NgModuleRef$1.get (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:24168:0)
JS:     at Object.get (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22071:0)
JS:     at getOrCreateInjectable (file: node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3921:0)
JS:     at Module.ɵɵdirectiveInject (file:///data/data/org.nativescript.stripe.demoangular/files...
```

During the update process, npm/angular warned about the zone-js version no more compatible with ng@10, so I updated it to the suggested version. 
I read the NS uses a modfied version of zone-js, to make it compatible with its environment. In order to use another version than the provided one, you need to follow some steps...which I'm going to read again now :P

**Comment by trane77** [comment]
Hello @RobertGardner, I've just pushed some changes, when you have some time can you check if the situation improved on your side? 

I don't think that zone-js was the problem, the current version is the one that comes with blank ns-ng projects. 

This update includes: 
- @nativescript/angular 10.0.0 (stable) instead of 10.0.0-rc.5 - in order to use this version, the page router outlet must be enclosed in any kind of layout element (like GridLayout, StackLayout, and so on), otherwise an exception is thrown at runtime. -
- Instead of having different tsconfig.*.json files, there's only one now in the demo projects. I don't know the reason behind the existence of the tsconfig.esm.json file, I never seen it in a nativescript project. Have you created them originally?

**Comment by lonemanotzi** [comment]
Getting error from  latest PR. Everything up to this command is ok.
npm run  build.plugin > 


`C:\nativescript-stripe-feature-nativescript-7-compat\demo-angular>npm run build.android

> @ build.android C:\nativescript-stripe-feature-nativescript-7-compat\demo-angular
> nsc build android

Copying template files...
Platform android successfully added. v6.5.3
Preparing project...
Hash: 61d65067832cd8f4e5b4
Version: webpack 4.44.1
Time: 21921ms
Built at: 08/19/2020 1:06:07 PM
 3 assets
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app.css] 1.13 KiB {bundle} [built]
[./main.ts] 1.13 KiB {bundle} [built]
[./package.json] 158 bytes {bundle} [optional] [built]
    + 327 hidden modules

ERROR in app/app.module.ts:3:38 - error TS2307: Cannot find module 'nativescript-stripe/angular' or its corresponding type declarations.

3 import { CreditCardViewModule } from "nativescript-stripe/angular";`

**Comment by RobertGardner** [comment]
To get it to work I still had to run `./pack.sh` and depend on the built package. Once I did that:

On Android it works better. All the buttons work, navigation works. The only problem is that the Standard Integration buttons still crash the app, with no indication of what happened. (No error messages, no log messages at all.)

On iOS it still fails. Navigation works again, though. Standard Integration crashes the app, though I do get an error in the logs (see below).  None of the Stripe integrations work except Images. The screens that have a credit card type-in field let me type in, but the buttons don't do anything. I don't see any error messages logged.

I get this warning when the app first launches. I'm not sure it's related to the crashes, though.
```
CONSOLE WARN Loading inspector modules failed:  Error: Could not find module 'inspector_modules.js'. Computed path '/Users/rgardner/Library/Developer/CoreSimulator/Devices/A90338A5-2162-4545-8ADB-81F79F344629/data/Containers/Bundle/Application/BD9B52B0-BBC6-4906-9726-5CA9F581423B/demoangular.app/app/tns_modules/inspector_modules.js'.
```

When the app crashes upon clicking the Standard Integration buttons, I get this error:
```
CONSOLE ERROR file: node_modules/@angular/core/fesm2015/core.js:4197:0: ERROR Error: Uncaught (in promise): Error: This value is not a native object.
n
CONSOLE ERROR file: node_modules/@angular/core/fesm2015/core.js:4197:0: ERROR Error: Uncaught (in promise): Error: Cannot instantiate cyclic dependency! StripeService
ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)
at throwCyclicDependencyError(file: node_modules/@angular/core/fesm2015/core.js:5438:0)
at hydrate(file: node_modules/@angular/core/fesm2015/core.js:11244:0)
at get(file: node_modules/@angular/core/fesm2015/core.js:11070:0)
at getOrCreateInjectable(file: node_modules/@angular/core/fesm2015/core.js:3921:0)
at IntentComponent_Factory(file: app/demo/intent.component.ts:13:28)
at getNodeInjectable(file: node_modules/@angular/core/fesm2015/core.js:4029:0)
at instantiateRootComponent(file: node_modules/@angular/core/fesm2015/core.js:7825:0)
at createRootComponent(file: node_modules/@angular/core/fesm2015/core.js:18374:0)
at create(file: node_modules/@angular/core/fesm2015/core.js:22190:0)
at createComponent(file: node_modules/@angular/core/fesm2015/core.js:10107:0)
at activateOnGoForward(file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:4556:0)
```
I have no idea what this is telling me, though!

**Comment by trane77** [comment]
Hello @RobertGardner, thank you for the detailed report. 

It's the first time that I see that output, I never worked with the iOS emulator so I cannot help with that, maybe @NathanWalker has got an idea about the source of this problem? 
By nose I would say that is related to an old reference in the objective c code that is not handling the new nativescript paths properly? 

Regarding the zone-js problem, I will debug it on Android to see more clearly, I suspect that is caused by how events are defined in the html markup. 

This gives me errors if I export the demo-angular code in another project, while it doesn't when running the demo directly inside of its folder:

```ts
<Button onTap=(card) />
```

This syntax instead is not giving me any warning:

```ts
<Button onTap=($event) />
```

I must test if this change fixes the zone-js problem. 

Stay tuned ;)

**Comment by RobertGardner** [comment]
According to the {N} blog, dated Aug. 31, "We will be introducing a new plugin seed soon with an improved architecture (over the current plugin seed), build tooling and setup to help you maintain all your plugins easier into the future. It will also allow easy drop in's of your existing plugins to use it (We will be dropping a blog post on this in next 2 weeks upon it's availability)."

What are your thoughts on waiting for this and restructuring once it comes out?

When I first built the demo apps I did it by just using `tns create ... ` and adding my components from there. I'm thinking that I should do the same thing again now that {N} v7 is released. That might cure some of the strange behavior we're seeing (and probably get rid of some of the weird files in the apps).

**Comment by triniwiz** [comment]
@RobertGardner as you mentioned the seed this plugin will be moved into a plugins mono repo (similar to the {N}) as it would make maintenance easier . I’m going to start the migration soon (after publishing a final 6.x version for another plugin

**Comment by trane77** [comment]
Hello everybody,
Today I've generated two new projects (with `ns create ...`): one in typescript and the other one in angular, then I've imported the existing demo projects into them. 
Also the dependencies where all updated to the stable version (`@nativescript/core` ... ) 

Well, now the demo project seems to work well with the new configuration, I don't know what will be introduced in the new plugin seed, but what can change more than this? Maybe the angular part, but that it's working good from what I can see. 

This is what I get when clicking on the first button now, is the first one that was giving problem: 
image

If you look at the html response, it's the response from heroku server. But I didn't configure it, I just replaced the url with xxx.heroku.com to bypass the check in the code. 

I've got a spring application already configured with stripe, if you can tell me which API call is trying to do, then I can configure it and finish this test. 

By the way tomorrow I'll give a last check to the code then push all the new updates, to let you check it too.

The demo(Ts) is giving another error when clicking on the button, but honestly I always worked with ns-angular, maybe the html markup must be updated, or something like this. 

Once this updated is over, what do you think about updating the underling sdk to v19? current version is 12. Is it a complex job to do?

PS @RobertGardner: I've taken this screenshot from the demo app, without packing the plugin: I think that the issue you had is solved somehow.

**Comment by aeliusdev** [comment]
Tried running this branch locally on iOS14:

```
import { Stripe, Card, StripeRedirectSession } from "nativescript-stripe";
const stripe = new Stripe([MY_STRIPE_KEY]);
const secret = [MY_SECRET];

stripe.authenticatePaymentIntent(secret, null, (error, pintent) => {
});
```

but I got this

```
====== Assertion failed ======
Native stack trace:
1          0x1065c7ceb tns::Assert(bool, v8::Isolate*) + 119
2          0x1065eae55 tns::Interop::WriteValue(v8::Local<v8::Context>, tns::TypeEncoding const*, void*, v8::Local<v8::Value>) + 5241
3          0x1065e99b6 tns::Interop::SetFFIParams(v8::Local<v8::Context>, tns::TypeEncoding const*, tns::FFICall*, int, int, tns::V8Args&) + 110
4          0x1065e962f tns::Interop::CallFunctionInternal(tns::MethodCall&) + 415
5          0x1065372f9 tns::ArgConverter::Invoke(v8::Local<v8::Context>, objc_class*, v8::Local<v8::Object>, tns::V8Args&, tns::MethodMeta const*, bool) + 735
6          0x10658f83a tns::MetadataBuilder::InvokeMethod(v8::Local<v8::Context>, tns::MethodMeta const*, v8::Local<v8::Object>, tns::V8Args&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) + 76
7          0x10658f111 tns::MetadataBuilder::MethodCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 219
8          0x1066ff22c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 620
9          0x1066fe6dc v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 556
10         0x1066fdd63 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 259
11         0x106f96d19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
12         0x106f2fd42 Builtins_InterpreterEntryTrampoline + 194
13         0x106f2fd42 Builtins_InterpreterEntryTrampoline + 194
14         0x106f2fd42 Builtins_InterpreterEntryTrampoline + 194
15         0x106fd7b2e Builtins_PromiseFulfillReactionJob + 46

JavaScript stack trace:
at authenticatePaymentIntent (file: app/Users/george/Downloads/stripe/src/stripe.ts:143:38)
```

Am I doing something wrong or this still in dev? Do you have an ETA? 

Thanks!

**Comment by trane77** [comment]
Hello @aeliusdev, currently I'm a bit out of time due to other project, there's an high probability that your code is ok, we are waiting for {N} team to release a new project seed, that we will use make this development fully compatible with the new nativescript v7 release.

Said that, are you using only that piece of code to test a payment? Please check the demo projects in the repository, they're almost up to date with the latest changes, check the Readme as well to see the right way of using this plugin.

**Comment by triniwiz** [comment]
@funder7 I'll be merge/migration

**Comment by trane77** [comment]
@triniwiz have you tested it? 
I wouldn't merge it on master branch yet, {N} team has just released some guidelines for plugin development, it's better to check if this PR against them.. ([blog post](https://nativescript.org/blog/announcing-plugin-workspaces/)

Just as recap before to consider the PR completed: 

- [ ] Test the plugin on both platforms
- [ ] Test demo projects updates
- [ ] Check if documentation and changelog files are ok
- [ ] Test new plugin pack script

**Comment by triniwiz** [comment]
Yeah I’m on that team and have been using the new repo before it was released  .. I’ll test it before 


Sent from Yahoo Mail for iPhone


On Saturday, September 19, 2020, 11:24 AM, Federico Ricchiuto <notifications@github.com> wrote:




@triniwiz have you tested it?
I wouldn't merge it on master branch yet, {N} team has just released some guidelines for plugin development, it's better to check if this PR against them.. (blog post

Just as recap before to consider the PR completed:
   
   -  Test the plugin on both platforms
   -  Test demo projects updates
   -  Check if documentation and changelog files are ok
   -  Test new plugin pack script

**Comment by trane77** [comment]
I just finished to import the project into the new plugin-seed, it's nice, but there are still problems with how the files are exported (demo projects cannot find some classes when importing them.. ).
Idk why it happens, honestly knowing the purpose of the "standard" folder would help me to understand the project better. 

@triniwiz if you know how to fix the missing bits, you're welcome.

**Comment by triniwiz** [comment]
@funder7 if you're done with this pr I'll merge this since this will be moved into a monorepo of the other plugins ... Thanks for the effort

**Comment by trane77** [comment]
Ok @triniwiz, yes I'm done with the PR, you can proceed with the merge if you want. 
You're welcome

**Comment by triniwiz** [comment]
Sweet!!! 🍺🍺🍺

**Comment by coderaven** [comment]
Hi! Any updates on this for a release we can use with NS7?

**Comment by ChadStrat** [comment]
bump. hoping for a NS7 update.

**Comment by triniwiz** [comment]
I'm currently working on the update also squeezing in the latest sdks on both platforms

**Comment by romandrahan** [comment]
@triniwiz, sorry, any update on this?

**Comment by triniwiz** [comment]
It's close I need to wrap some other things up first

**Comment by romandrahan** [comment]
Thanks, appreciate it.

**Comment by Stanteq** [comment]
I trying to use this PR on my app and it got this error:

```
ERROR in ../node_modules/nativescript-stripe/stripe.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /Volumes/Data/Projects/Mobelup/Mobelup/node_modules/nativescript-stripe/stripe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Volumes/Data/Projects/Mobelup/Mobelup/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:949:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (/Volumes/Data/Projects/Mobelup/Mobelup/node_modules/@nativescript/webpack/plugins/NativeScriptAngularCompilerPlugin.js:29:26)
    at /Volumes/Data/Projects/Mobelup/Mobelup/node_modules/@ngtools/webpack/src/loader.js:43:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 @ ./app/common/services/common.service.ts 24:0-45 235:31-37
 @ ./app/app.module.ts
 @ ./main.ts
```

**Comment by dmpvost** [comment]
Is it possible to try it? I'm interested too
thank for your job guys

**Comment by AgustinV08** [comment]
Are there any updates about this PR? A release date?

**Comment by msn444** [comment]
I'm also looking forward to this release.

BTW, I've tried to use the funder7:feature/nativescript-7-compat fork by installing the plugin from a local directory, but I get a multitude of errors such as:
      TS2307: Cannot find module '@nativescript/core' or its corresponding type declarations.
      TS2503: Cannot find namespace 'com'.
      TS2503: Cannot find namespace 'android'.
      TS2304: Cannot find name 'android'.

**Comment by msn444** [comment]
When running the typescript demo with NS7, I encounter the same problems I get with the master branch under NS7: 

**Android**: The app crashes immediately when I enter the Standard Integration screen, with the following error dump:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onClick failed
System.err: Error: java.lang.NullPointerException: Attempt to read from field 'int android.content.IntentFilter.mPriority' on a null object reference
System.err: 
System.err: StackTrace:
System.err: StripePaymentSession(file: src/Users/mikeneufeld/skywaylabsgit/software/nativescript-stripe/src/standard/standard.ts:126:144)
System.err:     at createPaymentSession(file: src/demo/stripe.service.ts:66:11)
System.err:     at navigatingTo(file: src/demo/std-page.ts:15:33)
System.err:     at _handleEvent(file: node_modules/@nativescript/core/data/observable/index.js:231:0)
System.err:     at notify(file: node_modules/@nativescript/core/data/observable/index.js:214:0)
...
```

**iOS**: I am able to enter the Standard Integration screen, get the customer key, select a payment method, enter shipping info. But when I hit "Buy", the app crashes as soon as the capturePayment method resolves with the https response. XCode reports 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

This is the same behaviour I was seeing on the master branch after migrating to NS7.

**Comment by trane77** [comment]
@msn444 have you upgraded the nativescript library installed globally?  
I mean: `npm i -g nativescript`.

To load the plugin from local repository:

1. Download the repository
2. Build the plugin in `src`  by running `npm run plugin.prepare`
3. Now you can pack the script with `cd ../publish && ./pack.sh`
4. A tgz archive will be created in the `publish/package/` folder, copy it's relative path
5. In your project's `package.json`, load the plugin by adding: 

`"nativescript-stripe": "file:../../nativescript-stripe/publish/package/nativescript-stripe-7.0.2-rc.0.tgz",`

As you can see the tgz archive is being loaded, with the path relative to the current folder (where package.json is located). 

The final step is to run `npm i` from your project , that will copy the plugin from the repository into your project's node_modules folder. 
Be sure that the generated tgz has the same version number or it will not be found.

I hope that these instructions will help you. If the typescript flavour doesn't work then you can use the angular one. I know , that's not the best solution.

**Considerations about the fork**
I did the upgrade mainly on the angular project, using android. The other flavours are being upgraded by @triniwiz , maybe he can give you and  @AgustinV08, @dmpvost some updates. I'd like to give my help too, but unfortunately I've got no time to work on this project now, I'm sorry for that.

**Comment by msn444** [comment]
Thanks for your efforts @funder7 
I'm able to avert the Android issue by commenting out the following from the `StripePaymentSession` constructor in standard.android.ts:
```
this.receiver = createShippingBroadcastReceiver(this, listener);

getLocalBroadcastManagerPackage().LocalBroadcastManager.getInstance(Application.android.foregroundActivity).registerReceiver(this.receiver, new android.content.IntentFilter(com.stripe.android.view.PaymentFlowExtras.EVENT_SHIPPING_INFO_SUBMITTED));
```
Since my application does not involve shipping, this works fine and I can process the payment without issue.

The iOS crash persists, however. More precisely, it occurs when `capturePayment` resolves and the `completion` callback is called. @triniwiz, do you have any insight?

**Comment by trane77** [comment]
@msn444 thanks for sharing those information, they would be useful for sure.

I don't know if the shipping doesn't work due to the recent ns7 upgrade & plugin compatibility, or its just because this plugin is based on an old version of stripe sdk.

It can be for both reasons. There's an issue about upgrading the sdk, actually it seems quite hard to accomplish.

I'm using stripe since less than a year, I don't know if the recent sdk versions introduced some breaking changes in the payment intent flow, o suppose that it's backward compatible though.

Thanks again for the info, I hope that they will be used.

Good luck with the implementation :)

**Comment by msn444** [comment]
@funder7 It seems I can just comment out the `completion` call and it doesn't crash. This way the payment goes through in the backend, but the SDK just never calls `onPaymentSuccess`. I can ascertain payment success via other means, so for now it might be a workable hack.

**Comment by ghost** [comment]
I'm getting assertion errors on iOS when using confirmSetupIntent()

```
const card1 = new Card('4242424242424242', 12, 20, '123');
const callback2 =  (err, si):void => {
  console.log(2, err, si.id);
};
const callback1 =  (err, pm):void => {
  console.log(1, err, pm.id);
  stripe.confirmSetupIntent(pm.id, clientSecret, callback2);
};
stripe.createPaymentMethod(card1, callback1);
```
====== Assertion failed ======
Native stack trace:
1          0x1050fc19f tns::Assert(bool, v8::Isolate*) + 119
2          0x105122df5 tns::Interop::WriteValue(v8::Local<v8::Context>, tns::TypeEncoding const*, void*, v8::Local<v8::Value>) + 5261
3          0x105121840 tns::Interop::SetFFIParams(v8::Local<v8::Context>, tns::TypeEncoding const*, tns::FFICall*, int, int, tns::V8Args&) + 110
4          0x1051214a5 tns::Interop::CallFunctionInternal(tns::MethodCall&) + 421
5          0x10505d4f0 tns::ArgConverter::Invoke(v8::Local<v8::Context>, objc_class*, v8::Local<v8::Object>, tns::V8Args&, tns::MethodMeta const*, bool) + 758
6          0x1050bde5a tns::MetadataBuilder::InvokeMethod(v8::Local<v8::Context>, tns::MethodMeta const*, v8::Local<v8::Object>, tns::V8Args&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) + 76
7          0x1050bd773 tns::MetadataBuilder::MethodCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 219
8          0x10524913c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 620
9          0x1052485ec v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 556
10         0x105247c73 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 259
11         0x105ae0c19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
JavaScript stack trace:
at confirmSetupIntent (file: node_modules/nativescript-stripe/stripe.ios.ts:100:38)
```

**Comment by toby-wollit** [comment]
changing `alloc()` to `alloc().init()` on the following two lines resolves the issue.

https://github.com/funder7/nativescript-stripe/blob/90dc236324648b81b540357e92fe824246d55b37/src/stripe.ios.ts#L162
https://github.com/funder7/nativescript-stripe/blob/90dc236324648b81b540357e92fe824246d55b37/src/stripe.ios.ts#L506

**Comment by msn444** [comment]
My next issue arises due to the fact that I am using Vue in my app. (My previous comments were based on working with the ts demo.) In a Vue project, I get an endless list of errors like this:

```
      TS2304: Cannot find name 'STPPaymentConfiguration'.
      TS2304: Cannot find name 'NSMutableSet'.
      TS2304: Cannot find name 'STPContactFieldName'.
      TS2304: Cannot find name 'STPContactFieldPostalAddress'.
      TS2304: Cannot find name 'STPContactFieldPhoneNumber'.
      TS2304: Cannot find name 'STPContactFieldEmailAddress'.
      TS2304: Cannot find name 'STPCustomerContext'.
```

Putting that aside, I now see that I can use the master 6.x branch with NS7+Vue if I simply remove type enforcement of the Page object in the stripe.service.ts file, along with the previously mentioned hacks. I will go this route until there is a stable NS7 version of the plugin.

**Comment by ghost** [comment]
@funder7 I have opened a pull request that fixes the issue i was experiencing. https://github.com/funder7/nativescript-stripe/pull/2

**Comment by triniwiz** [comment]
A small update I've finished the upgrade just need to update the docs before releasing 😄

**Comment by triniwiz** [comment]
Have something like this in mind for the docs

image

**Comment by triniwiz** [comment]
Feel free to test out the alpha using `@triniwiz/nativescript-stripe`

**Comment by triniwiz** [comment]
Thanks for all the feedback feel free to open any v7 issues in the new [monorepo](https://github.com/triniwiz/nativescript-plugins)

**Pull request closed without merging**
