### PR TITLE
New demo-angular README.md

### PR DESCRIPTION
**Pull request by rynop**
Addition of README.md to demo-angular that adds clarity to getting things up and working - including the tricky Apple Pay.

### CODE REVIEW

**Comment by RobertGardner** [comment]
Thanks!

There are scripts in src/package.json that simplify some of the steps you outline. For example, you can run the demos using `npm run demo-angular.ios` or `npm run demo.ios` (similar for `android`).

I think there should be a link to this new README in the main README, otherwise I'm not sure people will realize it's there. I also think most of the steps apply to the core NS demo app as well, but that can be another PR. (I can do that later.)

I'm not comfortable with the quote style changes and formatting changes made to `stripe.service.ts`. They make it hard to identify exactly which changes are required for this PR and they make the style of that file different than the other files in the app. I suspect those changes happened as part of your auto-save settings and may not have been made deliberately.

**Comment by rynop** [comment]
I'll update the quotes.  Sorry about that.  Yep autosave. I use the formatting defined by the Angular project.

Yea, was aware of the `scripts` in `src`, however it's a bit confusing and unorthodox IMO to have to go to another directory to run the app that you are currently in/working on. 

Totally agree on overlap between Angular and core NS demo apps.  I've never done Core NS, so didn't have the time ATM to figure out the deltas.

**Comment by rynop** [comment]
Ok fixed and re-wrote git history so its clean.  FWIW setting the empty strings in `demo-angular/app/demo/stripe.service.ts` fixes a TS error TS2339: Property 'endsWith' does not exist on type None.  TS compiles empty string down to non null safe type.

**Review by RobertGardner — CHANGES_REQUESTED** [review]
I'm doing this on a tablet in the plane so forgive the shorthand. 

Line 5: correct spelling of 'currently'
Line 21: correct spelling of 'setup'
Line 23: correct spelling of 'Capabilities'

I'm aware of the TS compile failure and have a script I run in the Travis continuous integration setup that puts values in there so it will compile. I debated doing that vs. dummy values like you've done and chose that route because I wanted to be able to throw an exception with a friendly message if the constants had not been set. It would be nice to still have a friendly exception message. If you want to change it to dummy values to avoid the compile error, could you check for that dummy value and throw the exception if they are still set? Look at line 35 in `stripe.service.ts`. I don't have a similar check for `publishableKey` since the Stripe SDK throws an error, but maybe there should be a check for that as well to provide a fail fast friendly message. Perhaps both constants could be checked in the constructor.

**Comment by rynop** [comment]
Fixed spelling (whoops, was in a hurry) & added placeholder value checks.

I also added docs on how to persist capabilities (aka entitlements).  I'm pretty confident https://github.com/Essent/nativescript-custom-entitlements is baked into nativescript cli since `v5.1.8`.  I tested this theory by `rm -rf platforms`, creating a `app/App_Resources/iOS/app.entitlements` and re-running `tns run ios`.  Verified on emulator and pysical device.  @RobertGardner if you could please also test this theory on your setup I'd appreciate the double check.

Lastly, a bit unrelated but while I got your attention :) does apple pay not work in custom integration due to the Stripe iOS SDK or just a current limitation of this plugin?  I really would like it for the app I'm making, so I'm trying to figure out the effort involved or the time I'll have to wait.  I don't have objective C/Swift skills, so unfortunately I can't contribute back if it is a plugin limitation.

**Comment by rynop** [comment]
Sorry one more thing that is unclear to me that I'd like to document.  https://github.com/stripe/example-ios-backend/blob/master/web.rb has no handler for `POST /charge` that is called [here](https://github.com/triniwiz/nativescript-stripe/blob/master/demo-angular/app/demo/stripe.service.ts#L66). 

My heroku example ios-backend logs show `POST /charge` being called and `200` returned, however I can't figure out what code is executing.

**Comment by rynop** [comment]
Ah jeez, stripe [just updated](https://github.com/stripe/example-ios-backend/commit/c465ad20b6b2ef575c05b72419f48edb8cfedfb7#diff-23d3ec39b62fa755f52022d83ef86578) their ios-backend example so now all of the examples that worked in this plugin are now broken. I'll create a new issue :(

**Pull request merged**
