### PR TITLE
Stripe Standard Integration Support

### PR DESCRIPTION
**Pull request by RobertGardner**
I have modified the nativescript-stripe plugin to implement the Stripe Standard Integration.

I started this awhile ago, working on it in my spare time. I noticed you recently updated the plugin to follow the latest plugin-seed and NS 4. I had made a number of similar modifications.

I would like to make this work available, but I'm not sure how you would like to handle this. I can think of several options. I'd like to get the path chosen before I put work into the final clean-up, since the path will determine quite a bit of what I do next.

Options:
1- Submit this work as part of nativescript-stripe
    a. Combine everything into one Stripe package
    b. Keep your custom integration and my standard integration packages largely separate
2- Instead, I approach nativescript-stripe-sdk and possibly put this code there
3- I submit this as a separate NPM package, probably nativescript-stripe-std

My first choice would be 1a, if that's acceptable to you.

Let me know how you'd like to proceed and I'll prepare another Pull Request.

### CODE REVIEW

**Comment by triniwiz** [comment]
Thanks I’ll review it and I like the same choice also I have plans to add Apple Pay and google pay 


Sent from Yahoo Mail for iPhone


On Sunday, August 26, 2018, 9:48 PM, Robert Gardner <notifications@github.com> wrote:


I have modified the nativescript-stripe plugin to implement the Stripe Standard Integration.

I started this awhile ago, working on it in my spare time. I noticed you recently updated the plugin to follow the latest plugin-seed and NS 4. I had made a number of similar modifications.

I would like to make this work available, but I'm not sure how you would like to handle this. I can think of several options. I'd like to get the path chosen before I put work into the final clean-up, since the path will determine quite a bit of what I do next.

Options:
1- Submit this work as part of nativescript-stripe
a. Combine everything into one Stripe package
b. Keep your custom integration and my standard integration packages largely separate
2- Instead, I approach nativescript-stripe-sdk and possibly put this code there
3- I submit this as a separate NPM package, probably nativescript-stripe-std

My first choice would be 1a, if that's acceptable to you.

Let me know how you'd like to proceed and I'll prepare another Pull Request.

You can view, comment on, or merge this pull request online at:

  https://github.com/triniwiz/nativescript-stripe/pull/18

Commit Summary
   
   - Get angular structure in place, using
   - Add some files that were accidentally gitignore'd.
   - Everything compiles. Crashes on execution.
   - Next phase - app launches and main page displays.
   - Step- App runs, pages look right, taps work, debugging works.
   - Fix problem with static inheritance in StripeConfig.
   - The UI comes up!
   - Update to newest Stripe SDK.
   - Restructure Angular demo to show off various integrations.
   - Make payment & shipping types dynamic, setting up for delegate.
   - Initial implementation of delegate.
   - Get shipping callback mostly working.
   - Get delegate working again.
   - Update total when shipping method changes.
   - Show ActivityIndicator while native STP module is loading.
   - Checkpoint: Payment callback is working!
   - Checkpoint: Move calls to client backend to stripe.service.
   - Checkpoint:
   - Remove iOS types from common interface.
   - Make CreditCardView and getToken platform independent.
   - Add "createToken" button to CCView Demo.
   - Set up Customers demo page.
   - Rename "item" folder to "demo".
   - Customers is server-side only, remove from demo.
   - Rename from XxxContext to XxxSession since that's more clear.
   - Early Android support, including upgrades to latest versions.
   - Get running on Android.
   - Initial android implementation.
   - Fix ClassNotFoundException.
   - Make sure listener is called on Android during all data/comm changes.
   - Properly handle shipping methods.
   - Correctly convert payment method.
   - Get charge flow basically working.
   - Move addressing hashing to client.
   - PaymentMethod now correctly handles async call to get customer.
   - Everything's working.
   - Update version.

File Changes
   
   -  M .gitignore (20) 
   -  A .travis.yml (74) 
   -  M CHANGELOG.md (5) 
   -  D angular/index.ts (2) 
   -  D angular/package.json (3) 
   -  A demo-angular/app/App_Resources/Android/AndroidManifest.xml (43) 
   -  A demo-angular/app/App_Resources/Android/app.gradle (16) 
   -  A demo-angular/app/App_Resources/Android/drawable-hdpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-hdpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-hdpi/logo.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-ldpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-ldpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-ldpi/logo.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-mdpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-mdpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-mdpi/logo.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-nodpi/splash_screen.xml (8) 
   -  A demo-angular/app/App_Resources/Android/drawable-xhdpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xhdpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xhdpi/logo.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xxhdpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xxhdpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xxhdpi/logo.png (0) 
   -  R demo-angular/app/App_Resources/Android/drawable-xxxhdpi/background.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xxxhdpi/icon.png (0) 
   -  A demo-angular/app/App_Resources/Android/drawable-xxxhdpi/logo.png (0) 
   -  A demo-angular/app/App_Resources/Android/values-v21/colors.xml (4) 
   -  A demo-angular/app/App_Resources/Android/values-v21/styles.xml (23) 
   -  A demo-angular/app/App_Resources/Android/values/colors.xml (7) 
   -  A demo-angular/app/App_Resources/Android/values/styles.xml (45) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/Contents.json (98) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-1024.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-29.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-29@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-29@3x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-40.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-76.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/Contents.json (6) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Contents.json (176) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-1125h.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-568h@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-667h@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-736h@3x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Landscape-X.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Landscape.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Landscape@3x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Portrait.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.AspectFill.imageset/Contents.json (22) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.AspectFill.imageset/LaunchScreen-AspectFill.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.AspectFill.imageset/LaunchScreen-AspectFill@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.Center.imageset/Contents.json (22) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.Center.imageset/LaunchScreen-Center.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.Center.imageset/LaunchScreen-Center@2x.png (0) 
   -  A demo-angular/app/App_Resources/iOS/Info.plist (47) 
   -  A demo-angular/app/App_Resources/iOS/LaunchScreen.storyboard (53) 
   -  A demo-angular/app/App_Resources/iOS/build.xcconfig (7) 
   -  A demo-angular/app/README.md (25) 
   -  A demo-angular/app/app.component.html (2) 
   -  A demo-angular/app/app.component.ts (8) 
   -  A demo-angular/app/app.css (12) 
   -  A demo-angular/app/app.module.ts (42) 
   -  A demo-angular/app/app.routing.ts (19) 
   -  A demo-angular/app/demo/creditcardview.component.html (9) 
   -  A demo-angular/app/demo/creditcardview.component.ts (21) 
   -  A demo-angular/app/demo/home.component.html (10) 
   -  A demo-angular/app/demo/home.component.ts (10) 
   -  A demo-angular/app/demo/item.ts (5) 
   -  A demo-angular/app/demo/standard.component.html (30) 
   -  A demo-angular/app/demo/standard.component.ts (137) 
   -  A demo-angular/app/demo/stripe.service.ts (106) 
   -  A demo-angular/app/main.ts (10) 
   -  A demo-angular/app/package.json (8) 
   -  A demo-angular/package-lock.json (1566) 
   -  A demo-angular/package.json (41) 
   -  R demo-angular/tsconfig.json (22) 
   -  M demo/app/main-page.ts (4) 
   -  M demo/package-lock.json (1312) 
   -  M demo/package.json (2) 
   -  A demo/references.d.ts (1) 
   -  M demo/tsconfig.json (1) 
   -  D index.d.ts (1) 
   -  D package-lock.json (147) 
   -  D package.json (62) 
   -  D platforms/android/include.gradle (11) 
   -  D platforms/ios/Podfile (1) 
   -  D src/android/card-view.d.ts (9) 
   -  M src/android/card-view.ts (11) 
   -  D src/android/card.d.ts (27) 
   -  M src/android/card.ts (83) 
   -  D src/android/stripe.d.ts (6) 
   -  M src/android/stripe.ts (285) 
   -  A src/angular/index.ts (1) 
   -  A src/angular/nativescript-stripe.directives.ts (8) 
   -  A src/angular/nativescript-stripe.module.ts (11) 
   -  A src/angular/package.json (4) 
   -  D src/card-view.common.d.ts (4) 
   -  D src/card-view.common.ts (7) 
   -  A src/common.ts (156) 
   -  A src/index.d.ts (205) 
   -  D src/ios/card-view.d.ts (9) 
   -  M src/ios/card-view.ts (84) 
   -  D src/ios/card.d.ts (28) 
   -  M src/ios/card.ts (101) 
   -  D src/ios/stripe.d.ts (4) 
   -  M src/ios/stripe.ts (291) 
   -  A src/java!Stripe.d.ts (2376) 
   -  R src/objc!Stripe.d.ts (8) 
   -  A src/package-lock.json (1589) 
   -  A src/package.json (72) 
   -  A src/platforms/android/AndroidManifest.xml (8) 
   -  A src/platforms/android/README.md (9) 
   -  A src/platforms/android/include.gradle (9) 
   -  A src/platforms/ios/Info.plist (7) 
   -  A src/platforms/ios/Podfile (2) 
   -  A src/platforms/ios/README.md (9) 
   -  R src/platforms/ios/build.xcconfig (0) 
   -  R src/references.d.ts (1) 
   -  A src/stripe.android.ts (3) 
   -  A src/stripe.ios.ts (3) 
   -  A src/tsconfig.json (35) 
   -  D stripe.android.d.ts (3) 
   -  D stripe.android.ts (3) 
   -  D stripe.ios.d.ts (3) 
   -  D stripe.ios.ts (3) 
   -  A tslint.json (57) 

Patch Links:
   
   - https://github.com/triniwiz/nativescript-stripe/pull/18.patch
   - https://github.com/triniwiz/nativescript-stripe/pull/18.diff

**Comment by triniwiz** [comment]
It looks good now only the conflicts and upgrading the ci you can check out the current version for that  😃

**Comment by RobertGardner** [comment]
Superb. I will do that, though it may take a week or two given the time I'm
able to dedicate to it.

**Comment by RobertGardner** [comment]
I've done the merge and gotten everything working. Check it out.

I had to revert the Stripe podfile version back to 11.2 since the latest version (starting with 11.4) contains breaking changes. I will work on bringing it up to the current version (13.2) next.

I updated the README, though I think the documentation I put there isn't superb. Hopefully the `demo-angular` example code will provide enough information on how to use it.

**Comment by triniwiz** [comment]
Thanks will look at it tomorrow 🙂

**Comment by RobertGardner** [comment]
I've updated to the latest iOS Stripe.

**Comment by triniwiz** [comment]
@RobertGardner it looks good but can you resolve the conflicts 😄

**Comment by RobertGardner** [comment]
I don't use GitHub on a regular basis so I'm struggling to figure out how to resolve the conflicts. It looks to me like only you (or someone with write access to triniwiz/nativescript-stripe) can resolve the conflicts. In case it will help, I enabled "Allow edits from maintainers."

I tried following the instructions at [Resolving a merge conflict using the command line](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/) but `git status` simply tells me everything is up to date and committed. I tried cloning the `triniwiz` repository and following the same instructions, but I also get the same result. I am suspicious that this can only be done by a `triniwiz` repository maintainer.

I have already merged `triniwiz/nativescript-stripe` into `RobertGardner/nativescript-stripe` to the best of my ability. So if you [check out my pull request locally](https://help.github.com/articles/checking-out-pull-requests-locally/) and are happy with things, you should be able to simply accept my version in all cases when resolving the conflicts. If you don't like what I did, feel free to commit modifications into my branch.

Sorry, that's the best I can do, unless you have instructions I've missed for how to do this better.

**Comment by RobertGardner** [comment]
Hi, I'm curious how this is coming and wondering if there's something I can
do to help.

For example, If you grant me temporary write access to the repository I can
do the reconciliation and send you the PR.

I was also wondering if I should break stripe.ts into two pieces, one for
the custom integration and one for the standard integration. Since people
are unlikely to use both at the same time, that might make sense. It would
also make it easier to evolve both integrations independently.

Thanks!
Robert

**Comment by triniwiz** [comment]
You can split it and i'll grant you access 😃

**Comment by RobertGardner** [comment]
Thanks. I started working on it and I think it will be a much better
organization. If I'd only known enough to do it this way in the first place!

**Comment by RobertGardner** [comment]
With the split into a `/standard` package, it will be easier to do this in stages. So I will close this PR and instead create a branch that I will use to (gradually) introduce all the code for this. I've created a new PR for the first step.

The steps will be:
1. Add the `/standard` package.
1. Add an `angular` demo app that demonstrates the new integration.
1. Add support for the existing integration to the `angular` demo app. This will require slightly modifying the existing integration to make it more similar across platforms.
1. Add support for the new integration to the existing demo app.

**Comment by RobertGardner** [comment]
I added a new branch and PR. I'd like you to look it over before it is
committed. Thanks!

**Pull request closed without merging**
